version: "2.2"
services:
    redis:
        image: "redis:alpine"
    aedes_b:
        build: ./aedes/
        volumes:
            - app-volume:/usr/src/app
    tcp_b:
        build: ./tcp/
        environment:
            REDIS_HOST: redis
        ports:
            - "7111:7111"
        volumes:
            - app-volume:/usr/src/aedes
        depends_on:
            - redis
            - aedes_b
volumes:
    app-volume:
