version: "2.2"
services:
    redis:
        image: "redis:alpine"
    aedes_b:
        build: ./aedes/
        environment:
            REDIS_HOST: redis
        volumes:
            - app-volume:/usr/src/app
    tcp_b:
        build: ./tcp/
        environment:
            REDIS_HOST: redis
        ports:
            - "7111:7111"
        volumes:
            - app-volume:/usr/src/aedes
        depends_on:
            - redis
            - aedes_b
    wss_b:
        build: ./wss/
        environment:
            REDIS_HOST: redis
            KEY_NAME: privkey.pem
            CERT_NAME: fullchain.pem
        ports:
            - "8111:8111"
        volumes:
            - app-volume:/usr/src/aedes
            - /root/aedesBroker:/usr/src/credentials
        depends_on:
            - redis
            - aedes_b
            - tcp_b
volumes:
    app-volume:
