version: "2.2"
services:
    redis:
        image: "redis:alpine"
    aedes_b:
        image: charles161/aedes_mqtt_broker:latest
        restart: always
        environment:
            REDIS_HOST: redis
            # AUTH_USERNAME: someuser
            # AUTH_PASSWORD: somepassword
            WSS_ENABLED: "true"
            KEY_NAME: privkey.pem
            CERT_NAME: fullchain.pem
        ports:
            - "7070:7070"
            - "8120:8120"
        volumes:
            - /root/aedesBroker:/usr/src/credentials
        depends_on:
            - redis
